### ISSUE TITLE
ssh_failure  command-error

### ISSUE THREAD

**Issue by tasos71** [treydock/ssh_exporter#21]
Hello, 

I am preparing an analysis of exporter outputs and I am trying to understand when the ssh_failure{reason="command-error"}   turns to 1.  From the title I understood that this error indicates an erroneous command.  I tried some use cases like a to run a root command with no sudo, or to list an non existing directory etc. At all these cases I get a  ssh_failure{reason="timeout"} 1 instead.  Also ssh_output{output=""}.  Does it make sense?

**Comment by treydock** [comment]
The command-error is only if the SSH golang code fails to run the command, has nothing to do with the exit code of the command.  SSH does not return exit codes that I'm aware of using Golang SSH library so the code has no way to know the command failed unless you set `command_expect` in the config file to tell the exporter what output to expect.

You are getting that timeout reason because the duration of the SSH command exceeds the default timeout of 10 seconds.  You could likely verify this if you use curl with time command to see if the scrape takes close to 10 seconds before returning metrics.
