### ISSUE TITLE
Failure of the SSH command shows as a timeout

### ISSUE THREAD

**Issue by qdii** [treydock/ssh_exporter#24]
When the executed SSH command returns non-0, the go routine simply exits. As a result, the select statement takes the "exit with a timeout" case.

**Comment by treydock** [comment]
SSH does not know how to return exit codes so the exit status of the command doesn't matter and no way to collect it unless you echo it and compare output.  The command failure you removed in #25 is if the SSH command fails, but not because of exit status.  I'd need more information and a way to reproduce because stripping out the bit of code would make some problems never get caught.

**Comment by treydock** [comment]
I found a way to reproduce, ignore deleted comment.
